const BOOKS = [
	{
		name: "Genesis",
		aliases: ["Gen"],
		meta: {
			total_chapters: 50,
			content: [
				{ verses: 31 },
				{ verses: 25 },
				{ verses: 24 },
				{ verses: 26 },
				{ verses: 32 },
				{ verses: 22 },
				{ verses: 24 },
				{ verses: 22 },
				{ verses: 29 },
				{ verses: 32 },
				{ verses: 32 },
				{ verses: 20 },
				{ verses: 18 },
				{ verses: 24 },
				{ verses: 21 },
				{ verses: 16 },
				{ verses: 27 },
				{ verses: 33 },
				{ verses: 38 },
				{ verses: 18 },
				{ verses: 34 },
				{ verses: 24 },
				{ verses: 20 },
				{ verses: 67 },
				{ verses: 34 },
				{ verses: 35 },
				{ verses: 46 },
				{ verses: 22 },
				{ verses: 35 },
				{ verses: 43 },
				{ verses: 55 },
				{ verses: 32 },
				{ verses: 20 },
				{ verses: 31 },
				{ verses: 29 },
				{ verses: 43 },
				{ verses: 36 },
				{ verses: 30 },
				{ verses: 23 },
				{ verses: 23 },
				{ verses: 57 },
				{ verses: 38 },
				{ verses: 34 },
				{ verses: 34 },
				{ verses: 28 },
				{ verses: 34 },
				{ verses: 31 },
				{ verses: 22 },
				{ verses: 33 },
				{ verses: 26 },
			],
		},
	},
	{
		name: "Exodus",
		aliases: ["Exod", "Ex", "Exo"],
		meta: {
			total_chapters: 40,
			content: [
				{ verses: 22 },
				{ verses: 25 },
				{ verses: 22 },
				{ verses: 31 },
				{ verses: 23 },
				{ verses: 30 },
				{ verses: 25 },
				{ verses: 32 },
				{ verses: 35 },
				{ verses: 29 },
				{ verses: 10 },
				{ verses: 51 },
				{ verses: 22 },
				{ verses: 31 },
				{ verses: 27 },
				{ verses: 36 },
				{ verses: 16 },
				{ verses: 27 },
				{ verses: 25 },
				{ verses: 26 },
				{ verses: 37 },
				{ verses: 31 },
				{ verses: 33 },
				{ verses: 18 },
				{ verses: 40 },
				{ verses: 37 },
				{ verses: 21 },
				{ verses: 43 },
				{ verses: 46 },
				{ verses: 38 },
				{ verses: 18 },
				{ verses: 35 },
				{ verses: 23 },
				{ verses: 35 },
				{ verses: 35 },
				{ verses: 38 },
				{ verses: 29 },
				{ verses: 31 },
				{ verses: 43 },
				{ verses: 38 },
			],
		},
	},
	{
		name: "Leviticus",
		aliases: ["Lev"],
		meta: {
			total_chapters: 27,
			content: [
				{ verses: 17 },
				{ verses: 16 },
				{ verses: 17 },
				{ verses: 35 },
				{ verses: 19 },
				{ verses: 30 },
				{ verses: 38 },
				{ verses: 36 },
				{ verses: 24 },
				{ verses: 20 },
				{ verses: 47 },
				{ verses: 8 },
				{ verses: 59 },
				{ verses: 58 },
				{ verses: 33 },
				{ verses: 34 },
				{ verses: 16 },
				{ verses: 30 },
				{ verses: 37 },
				{ verses: 27 },
				{ verses: 24 },
				{ verses: 33 },
				{ verses: 44 },
				{ verses: 23 },
				{ verses: 55 },
				{ verses: 46 },
				{ verses: 34 },
			],
		},
	},
	{
		name: "Numbers",
		aliases: ["Num"],
		meta: {
			total_chapters: 36,
			content: [
				{ verses: 54 },
				{ verses: 34 },
				{ verses: 51 },
				{ verses: 49 },
				{ verses: 31 },
				{ verses: 27 },
				{ verses: 89 },
				{ verses: 26 },
				{ verses: 23 },
				{ verses: 36 },
				{ verses: 35 },
				{ verses: 16 },
				{ verses: 33 },
				{ verses: 45 },
				{ verses: 41 },
				{ verses: 50 },
				{ verses: 13 },
				{ verses: 32 },
				{ verses: 22 },
				{ verses: 29 },
				{ verses: 35 },
				{ verses: 41 },
				{ verses: 30 },
				{ verses: 25 },
				{ verses: 18 },
				{ verses: 65 },
				{ verses: 23 },
				{ verses: 31 },
				{ verses: 40 },
				{ verses: 16 },
				{ verses: 54 },
				{ verses: 42 },
				{ verses: 56 },
				{ verses: 29 },
				{ verses: 34 },
				{ verses: 13 },
			],
		},
	},
	{
		name: "Deuteronomy",
		aliases: ["Deut"],
		meta: {
			total_chapters: 34,
			content: [
				{ verses: 46 },
				{ verses: 37 },
				{ verses: 29 },
				{ verses: 49 },
				{ verses: 33 },
				{ verses: 25 },
				{ verses: 26 },
				{ verses: 20 },
				{ verses: 29 },
				{ verses: 22 },
				{ verses: 32 },
				{ verses: 32 },
				{ verses: 18 },
				{ verses: 29 },
				{ verses: 23 },
				{ verses: 22 },
				{ verses: 20 },
				{ verses: 22 },
				{ verses: 21 },
				{ verses: 20 },
				{ verses: 23 },
				{ verses: 30 },
				{ verses: 25 },
				{ verses: 22 },
				{ verses: 19 },
				{ verses: 19 },
				{ verses: 26 },
				{ verses: 68 },
				{ verses: 29 },
				{ verses: 20 },
				{ verses: 30 },
				{ verses: 52 },
				{ verses: 29 },
				{ verses: 12 },
			],
		},
	},
	{
		name: "Joshua",
		aliases: ["Josh"],
		meta: {
			total_chapters: 24,
			content: [
				{ verses: 18 },
				{ verses: 24 },
				{ verses: 17 },
				{ verses: 24 },
				{ verses: 15 },
				{ verses: 27 },
				{ verses: 26 },
				{ verses: 35 },
				{ verses: 27 },
				{ verses: 43 },
				{ verses: 23 },
				{ verses: 24 },
				{ verses: 33 },
				{ verses: 15 },
				{ verses: 63 },
				{ verses: 10 },
				{ verses: 18 },
				{ verses: 28 },
				{ verses: 51 },
				{ verses: 9 },
				{ verses: 45 },
				{ verses: 34 },
				{ verses: 16 },
				{ verses: 33 },
			],
		},
	},
	{
		name: "Judges",
		aliases: ["Judg"],
		meta: {
			total_chapters: 21,
			content: [
				{ verses: 36 },
				{ verses: 23 },
				{ verses: 31 },
				{ verses: 24 },
				{ verses: 31 },
				{ verses: 40 },
				{ verses: 25 },
				{ verses: 35 },
				{ verses: 57 },
				{ verses: 18 },
				{ verses: 40 },
				{ verses: 15 },
				{ verses: 25 },
				{ verses: 20 },
				{ verses: 20 },
				{ verses: 31 },
				{ verses: 13 },
				{ verses: 31 },
				{ verses: 30 },
				{ verses: 48 },
				{ verses: 25 },
			],
		},
	},
	{
		name: "Ruth",
		aliases: [],
		meta: {
			total_chapters: 4,
			content: [{ verses: 22 }, { verses: 23 }, { verses: 18 }, { verses: 22 }],
		},
	},
	{
		name: "1 Samuel",
		aliases: ["1 Sam", "1st Sam", "1st Samuel", "First Samuel"],
		meta: {
			total_chapters: 31,
			content: [
				{ verses: 28 },
				{ verses: 36 },
				{ verses: 21 },
				{ verses: 22 },
				{ verses: 12 },
				{ verses: 21 },
				{ verses: 17 },
				{ verses: 22 },
				{ verses: 27 },
				{ verses: 27 },
				{ verses: 15 },
				{ verses: 25 },
				{ verses: 23 },
				{ verses: 52 },
				{ verses: 35 },
				{ verses: 23 },
				{ verses: 58 },
				{ verses: 30 },
				{ verses: 24 },
				{ verses: 43 },
				{ verses: 15 },
				{ verses: 23 },
				{ verses: 29 },
				{ verses: 22 },
				{ verses: 44 },
				{ verses: 25 },
				{ verses: 12 },
				{ verses: 25 },
				{ verses: 11 },
				{ verses: 31 },
				{ verses: 13 },
			],
		},
	},
	{
		name: "2 Samuel",
		aliases: ["2 Sam", "2nd Sam", "2nd Samuel", "Second Samuel"],
		meta: {
			total_chapters: 24,
			content: [
				{ verses: 27 },
				{ verses: 32 },
				{ verses: 39 },
				{ verses: 12 },
				{ verses: 25 },
				{ verses: 24 },
				{ verses: 29 },
				{ verses: 18 },
				{ verses: 13 },
				{ verses: 19 },
				{ verses: 27 },
				{ verses: 31 },
				{ verses: 39 },
				{ verses: 33 },
				{ verses: 37 },
				{ verses: 23 },
				{ verses: 29 },
				{ verses: 33 },
				{ verses: 43 },
				{ verses: 26 },
				{ verses: 22 },
				{ verses: 51 },
				{ verses: 39 },
				{ verses: 25 },
			],
		},
	},
	{
		name: "1 Kings",
		aliases: ["1 Kgs", "1st Kgs", "1st Kings", "First Kings"],
		meta: {
			total_chapters: 22,
			content: [
				{ verses: 53 },
				{ verses: 46 },
				{ verses: 28 },
				{ verses: 34 },
				{ verses: 18 },
				{ verses: 38 },
				{ verses: 51 },
				{ verses: 66 },
				{ verses: 28 },
				{ verses: 29 },
				{ verses: 43 },
				{ verses: 33 },
				{ verses: 34 },
				{ verses: 31 },
				{ verses: 34 },
				{ verses: 34 },
				{ verses: 24 },
				{ verses: 46 },
				{ verses: 21 },
				{ verses: 43 },
				{ verses: 29 },
				{ verses: 53 },
			],
		},
	},
	{
		name: "2 Kings",
		aliases: ["2 Kgs", "2nd Kgs", "2nd Kings", "Second Kings"],
		meta: {
			total_chapters: 25,
			content: [
				{ verses: 18 },
				{ verses: 25 },
				{ verses: 27 },
				{ verses: 44 },
				{ verses: 27 },
				{ verses: 33 },
				{ verses: 20 },
				{ verses: 29 },
				{ verses: 37 },
				{ verses: 36 },
				{ verses: 21 },
				{ verses: 21 },
				{ verses: 25 },
				{ verses: 29 },
				{ verses: 38 },
				{ verses: 20 },
				{ verses: 41 },
				{ verses: 37 },
				{ verses: 37 },
				{ verses: 21 },
				{ verses: 26 },
				{ verses: 20 },
				{ verses: 37 },
				{ verses: 20 },
				{ verses: 30 },
			],
		},
	},
	{
		name: "1 Chronicles",
		aliases: ["1 Chr", "1st Chr", "1st Chronicles", "First Chronicles"],
		meta: {
			total_chapters: 29,
			content: [
				{ verses: 54 },
				{ verses: 55 },
				{ verses: 24 },
				{ verses: 43 },
				{ verses: 26 },
				{ verses: 81 },
				{ verses: 40 },
				{ verses: 40 },
				{ verses: 44 },
				{ verses: 14 },
				{ verses: 47 },
				{ verses: 40 },
				{ verses: 14 },
				{ verses: 17 },
				{ verses: 29 },
				{ verses: 43 },
				{ verses: 27 },
				{ verses: 17 },
				{ verses: 19 },
				{ verses: 8 },
				{ verses: 30 },
				{ verses: 19 },
				{ verses: 32 },
				{ verses: 31 },
				{ verses: 31 },
				{ verses: 32 },
				{ verses: 34 },
				{ verses: 21 },
				{ verses: 30 },
			],
		},
	},
	{
		name: "2 Chronicles",
		aliases: ["2 Chr", "2nd Chr", "2nd Chronicles", "Second Chronicles"],
		meta: {
			total_chapters: 36,
			content: [
				{ verses: 17 },
				{ verses: 18 },
				{ verses: 17 },
				{ verses: 22 },
				{ verses: 14 },
				{ verses: 42 },
				{ verses: 22 },
				{ verses: 18 },
				{ verses: 31 },
				{ verses: 19 },
				{ verses: 23 },
				{ verses: 16 },
				{ verses: 22 },
				{ verses: 15 },
				{ verses: 19 },
				{ verses: 14 },
				{ verses: 19 },
				{ verses: 34 },
				{ verses: 11 },
				{ verses: 37 },
				{ verses: 20 },
				{ verses: 12 },
				{ verses: 21 },
				{ verses: 27 },
				{ verses: 28 },
				{ verses: 23 },
				{ verses: 9 },
				{ verses: 27 },
				{ verses: 36 },
				{ verses: 27 },
				{ verses: 21 },
				{ verses: 33 },
				{ verses: 25 },
				{ verses: 33 },
				{ verses: 27 },
				{ verses: 23 },
			],
		},
	},
	{
		name: "Ezra",
		aliases: ["Ezra"],
		meta: {
			total_chapters: 10,
			content: [
				{ verses: 11 },
				{ verses: 70 },
				{ verses: 13 },
				{ verses: 24 },
				{ verses: 17 },
				{ verses: 22 },
				{ verses: 28 },
				{ verses: 36 },
				{ verses: 15 },
				{ verses: 44 },
			],
		},
	},
	{
		name: "Nehemiah",
		aliases: ["Neh"],
		meta: {
			total_chapters: 13,
			content: [
				{ verses: 11 },
				{ verses: 20 },
				{ verses: 32 },
				{ verses: 23 },
				{ verses: 19 },
				{ verses: 19 },
				{ verses: 73 },
				{ verses: 18 },
				{ verses: 38 },
				{ verses: 39 },
				{ verses: 36 },
				{ verses: 47 },
				{ verses: 31 },
			],
		},
	},
	{
		name: "Esther",
		aliases: ["Esth", "Est"],
		meta: {
			total_chapters: 10,
			content: [
				{ verses: 22 },
				{ verses: 23 },
				{ verses: 15 },
				{ verses: 17 },
				{ verses: 14 },
				{ verses: 14 },
				{ verses: 10 },
				{ verses: 17 },
				{ verses: 32 },
				{ verses: 3 },
			],
		},
	},
	{
		name: "Job",
		aliases: [],
		meta: {
			total_chapters: 42,
			content: [
				{ verses: 22 },
				{ verses: 13 },
				{ verses: 26 },
				{ verses: 21 },
				{ verses: 27 },
				{ verses: 30 },
				{ verses: 21 },
				{ verses: 22 },
				{ verses: 35 },
				{ verses: 22 },
				{ verses: 20 },
				{ verses: 25 },
				{ verses: 28 },
				{ verses: 22 },
				{ verses: 35 },
				{ verses: 22 },
				{ verses: 16 },
				{ verses: 21 },
				{ verses: 29 },
				{ verses: 29 },
				{ verses: 34 },
				{ verses: 30 },
				{ verses: 17 },
				{ verses: 25 },
				{ verses: 6 },
				{ verses: 14 },
				{ verses: 23 },
				{ verses: 28 },
				{ verses: 25 },
				{ verses: 31 },
				{ verses: 40 },
				{ verses: 22 },
				{ verses: 33 },
				{ verses: 37 },
				{ verses: 16 },
				{ verses: 33 },
				{ verses: 24 },
				{ verses: 41 },
				{ verses: 30 },
				{ verses: 24 },
				{ verses: 34 },
				{ verses: 17 },
			],
		},
	},
	{
		name: "Psalms",
		aliases: ["Ps", "Psalm"],
		meta: {
			total_chapters: 150,
			content: [
				{ verses: 6 },
				{ verses: 12 },
				{ verses: 8 },
				{ verses: 8 },
				{ verses: 12 },
				{ verses: 10 },
				{ verses: 17 },
				{ verses: 9 },
				{ verses: 20 },
				{ verses: 18 },
				{ verses: 7 },
				{ verses: 8 },
				{ verses: 6 },
				{ verses: 7 },
				{ verses: 5 },
				{ verses: 11 },
				{ verses: 15 },
				{ verses: 50 },
				{ verses: 14 },
				{ verses: 9 },
				{ verses: 13 },
				{ verses: 31 },
				{ verses: 6 },
				{ verses: 10 },
				{ verses: 22 },
				{ verses: 12 },
				{ verses: 14 },
				{ verses: 9 },
				{ verses: 11 },
				{ verses: 12 },
				{ verses: 24 },
				{ verses: 11 },
				{ verses: 22 },
				{ verses: 22 },
				{ verses: 28 },
				{ verses: 12 },
				{ verses: 40 },
				{ verses: 22 },
				{ verses: 13 },
				{ verses: 17 },
				{ verses: 13 },
				{ verses: 11 },
				{ verses: 5 },
				{ verses: 26 },
				{ verses: 17 },
				{ verses: 11 },
				{ verses: 9 },
				{ verses: 14 },
				{ verses: 20 },
				{ verses: 23 },
				{ verses: 19 },
				{ verses: 9 },
				{ verses: 6 },
				{ verses: 7 },
				{ verses: 23 },
				{ verses: 13 },
				{ verses: 11 },
				{ verses: 11 },
				{ verses: 17 },
				{ verses: 12 },
				{ verses: 8 },
				{ verses: 12 },
				{ verses: 11 },
				{ verses: 10 },
				{ verses: 13 },
				{ verses: 20 },
				{ verses: 7 },
				{ verses: 35 },
				{ verses: 36 },
				{ verses: 5 },
				{ verses: 24 },
				{ verses: 20 },
				{ verses: 28 },
				{ verses: 23 },
				{ verses: 10 },
				{ verses: 12 },
				{ verses: 20 },
				{ verses: 72 },
				{ verses: 13 },
				{ verses: 19 },
				{ verses: 16 },
				{ verses: 8 },
				{ verses: 18 },
				{ verses: 12 },
				{ verses: 13 },
				{ verses: 17 },
				{ verses: 7 },
				{ verses: 18 },
				{ verses: 52 },
				{ verses: 17 },
				{ verses: 16 },
				{ verses: 15 },
				{ verses: 5 },
				{ verses: 23 },
				{ verses: 11 },
				{ verses: 13 },
				{ verses: 12 },
				{ verses: 9 },
				{ verses: 9 },
				{ verses: 5 },
				{ verses: 8 },
				{ verses: 28 },
				{ verses: 22 },
				{ verses: 35 },
				{ verses: 45 },
				{ verses: 48 },
				{ verses: 43 },
				{ verses: 13 },
				{ verses: 31 },
				{ verses: 7 },
				{ verses: 10 },
				{ verses: 10 },
				{ verses: 9 },
				{ verses: 8 },
				{ verses: 18 },
				{ verses: 19 },
				{ verses: 2 },
				{ verses: 29 },
				{ verses: 176 },
				{ verses: 7 },
				{ verses: 8 },
				{ verses: 9 },
				{ verses: 4 },
				{ verses: 8 },
				{ verses: 5 },
				{ verses: 6 },
				{ verses: 5 },
				{ verses: 6 },
				{ verses: 8 },
				{ verses: 8 },
				{ verses: 3 },
				{ verses: 18 },
				{ verses: 3 },
				{ verses: 3 },
				{ verses: 21 },
				{ verses: 26 },
				{ verses: 9 },
				{ verses: 8 },
				{ verses: 24 },
				{ verses: 13 },
				{ verses: 10 },
				{ verses: 7 },
				{ verses: 12 },
				{ verses: 15 },
				{ verses: 21 },
				{ verses: 10 },
				{ verses: 20 },
				{ verses: 14 },
				{ verses: 9 },
				{ verses: 6 },
			],
		},
	},
	{
		name: "Proverbs",
		aliases: ["Prov", "Pro"],
		meta: {
			total_chapters: 31,
			content: [
				{ verses: 33 },
				{ verses: 22 },
				{ verses: 35 },
				{ verses: 27 },
				{ verses: 23 },
				{ verses: 35 },
				{ verses: 27 },
				{ verses: 36 },
				{ verses: 18 },
				{ verses: 32 },
				{ verses: 31 },
				{ verses: 28 },
				{ verses: 25 },
				{ verses: 35 },
				{ verses: 33 },
				{ verses: 33 },
				{ verses: 28 },
				{ verses: 24 },
				{ verses: 29 },
				{ verses: 30 },
				{ verses: 31 },
				{ verses: 29 },
				{ verses: 35 },
				{ verses: 34 },
				{ verses: 29 },
				{ verses: 28 },
				{ verses: 27 },
				{ verses: 28 },
				{ verses: 27 },
				{ verses: 33 },
				{ verses: 31 },
			],
		},
	},
	{
		name: "Ecclesiastes",
		aliases: ["Eccl", "Ecc"],
		meta: {
			total_chapters: 12,
			content: [
				{ verses: 18 },
				{ verses: 26 },
				{ verses: 22 },
				{ verses: 16 },
				{ verses: 20 },
				{ verses: 12 },
				{ verses: 29 },
				{ verses: 17 },
				{ verses: 18 },
				{ verses: 20 },
				{ verses: 10 },
				{ verses: 14 },
			],
		},
	},
	{
		name: "Song of Solomon",
		aliases: ["Song", "Song of Songs"],
		meta: {
			total_chapters: 8,
			content: [
				{ verses: 17 },
				{ verses: 17 },
				{ verses: 11 },
				{ verses: 16 },
				{ verses: 16 },
				{ verses: 13 },
				{ verses: 13 },
				{ verses: 14 },
			],
		},
	},
	{
		name: "Isaiah",
		aliases: ["Isa"],
		meta: {
			total_chapters: 66,
			content: [
				{ verses: 31 },
				{ verses: 22 },
				{ verses: 26 },
				{ verses: 6 },
				{ verses: 30 },
				{ verses: 13 },
				{ verses: 25 },
				{ verses: 22 },
				{ verses: 21 },
				{ verses: 34 },
				{ verses: 16 },
				{ verses: 6 },
				{ verses: 22 },
				{ verses: 32 },
				{ verses: 9 },
				{ verses: 14 },
				{ verses: 14 },
				{ verses: 7 },
				{ verses: 25 },
				{ verses: 6 },
				{ verses: 17 },
				{ verses: 25 },
				{ verses: 18 },
				{ verses: 23 },
				{ verses: 12 },
				{ verses: 21 },
				{ verses: 13 },
				{ verses: 29 },
				{ verses: 24 },
				{ verses: 33 },
				{ verses: 9 },
				{ verses: 20 },
				{ verses: 24 },
				{ verses: 17 },
				{ verses: 10 },
				{ verses: 22 },
				{ verses: 38 },
				{ verses: 22 },
				{ verses: 8 },
				{ verses: 31 },
				{ verses: 29 },
				{ verses: 25 },
				{ verses: 28 },
				{ verses: 28 },
				{ verses: 25 },
				{ verses: 13 },
				{ verses: 15 },
				{ verses: 22 },
				{ verses: 26 },
				{ verses: 11 },
				{ verses: 23 },
				{ verses: 15 },
				{ verses: 12 },
				{ verses: 17 },
				{ verses: 13 },
				{ verses: 12 },
				{ verses: 21 },
				{ verses: 14 },
				{ verses: 21 },
				{ verses: 22 },
				{ verses: 11 },
				{ verses: 12 },
				{ verses: 19 },
				{ verses: 12 },
				{ verses: 25 },
				{ verses: 24 },
			],
		},
	},
	{
		name: "Jeremiah",
		aliases: ["Jer"],
		meta: {
			total_chapters: 52,
			content: [
				{ verses: 19 },
				{ verses: 37 },
				{ verses: 25 },
				{ verses: 31 },
				{ verses: 31 },
				{ verses: 30 },
				{ verses: 34 },
				{ verses: 22 },
				{ verses: 26 },
				{ verses: 25 },
				{ verses: 23 },
				{ verses: 17 },
				{ verses: 27 },
				{ verses: 22 },
				{ verses: 21 },
				{ verses: 21 },
				{ verses: 27 },
				{ verses: 23 },
				{ verses: 15 },
				{ verses: 18 },
				{ verses: 14 },
				{ verses: 30 },
				{ verses: 40 },
				{ verses: 10 },
				{ verses: 38 },
				{ verses: 24 },
				{ verses: 22 },
				{ verses: 17 },
				{ verses: 32 },
				{ verses: 24 },
				{ verses: 40 },
				{ verses: 44 },
				{ verses: 26 },
				{ verses: 22 },
				{ verses: 19 },
				{ verses: 32 },
				{ verses: 21 },
				{ verses: 28 },
				{ verses: 18 },
				{ verses: 16 },
				{ verses: 18 },
				{ verses: 22 },
				{ verses: 13 },
				{ verses: 30 },
				{ verses: 5 },
				{ verses: 28 },
				{ verses: 7 },
				{ verses: 47 },
				{ verses: 39 },
				{ verses: 46 },
				{ verses: 64 },
				{ verses: 34 },
			],
		},
	},
	{
		name: "Lamentations",
		aliases: ["Lam"],
		meta: {
			total_chapters: 5,
			content: [
				{ verses: 22 },
				{ verses: 22 },
				{ verses: 66 },
				{ verses: 22 },
				{ verses: 22 },
			],
		},
	},
	{
		name: "Ezekiel",
		aliases: ["Ezek"],
		meta: {
			total_chapters: 48,
			content: [
				{ verses: 28 },
				{ verses: 10 },
				{ verses: 27 },
				{ verses: 17 },
				{ verses: 17 },
				{ verses: 14 },
				{ verses: 27 },
				{ verses: 18 },
				{ verses: 11 },
				{ verses: 22 },
				{ verses: 25 },
				{ verses: 28 },
				{ verses: 23 },
				{ verses: 23 },
				{ verses: 8 },
				{ verses: 63 },
				{ verses: 24 },
				{ verses: 32 },
				{ verses: 14 },
				{ verses: 49 },
				{ verses: 32 },
				{ verses: 31 },
				{ verses: 49 },
				{ verses: 27 },
				{ verses: 17 },
				{ verses: 21 },
				{ verses: 37 },
				{ verses: 26 },
				{ verses: 21 },
				{ verses: 26 },
				{ verses: 18 },
				{ verses: 32 },
				{ verses: 33 },
				{ verses: 31 },
				{ verses: 15 },
				{ verses: 38 },
				{ verses: 28 },
				{ verses: 23 },
				{ verses: 29 },
				{ verses: 49 },
				{ verses: 26 },
				{ verses: 20 },
				{ verses: 27 },
				{ verses: 31 },
				{ verses: 25 },
				{ verses: 24 },
				{ verses: 23 },
				{ verses: 35 },
			],
		},
	},
	{
		name: "Daniel",
		aliases: ["Dan"],
		meta: {
			total_chapters: 12,
			content: [
				{ verses: 21 },
				{ verses: 49 },
				{ verses: 30 },
				{ verses: 37 },
				{ verses: 31 },
				{ verses: 28 },
				{ verses: 28 },
				{ verses: 27 },
				{ verses: 27 },
				{ verses: 21 },
				{ verses: 45 },
				{ verses: 13 },
			],
		},
	},
	{
		name: "Hosea",
		aliases: ["Hos"],
		meta: {
			total_chapters: 14,
			content: [
				{ verses: 11 },
				{ verses: 23 },
				{ verses: 5 },
				{ verses: 19 },
				{ verses: 15 },
				{ verses: 11 },
				{ verses: 16 },
				{ verses: 14 },
				{ verses: 17 },
				{ verses: 15 },
				{ verses: 12 },
				{ verses: 14 },
				{ verses: 16 },
				{ verses: 9 },
			],
		},
	},
	{
		name: "Joel",
		aliases: [],
		meta: {
			total_chapters: 3,
			content: [{ verses: 20 }, { verses: 32 }, { verses: 21 }],
		},
	},
	{
		name: "Amos",
		aliases: [],
		meta: {
			total_chapters: 9,
			content: [
				{ verses: 15 },
				{ verses: 16 },
				{ verses: 15 },
				{ verses: 13 },
				{ verses: 27 },
				{ verses: 14 },
				{ verses: 17 },
				{ verses: 14 },
				{ verses: 15 },
			],
		},
	},
	{
		name: "Obadiah",
		aliases: ["Obad", "Oba"],
		meta: { total_chapters: 1, content: [{ verses: 22 }] },
	},
	{
		name: "Jonah",
		aliases: ["Jon"],
		meta: {
			total_chapters: 4,
			content: [{ verses: 17 }, { verses: 10 }, { verses: 10 }, { verses: 11 }],
		},
	},
	{
		name: "Micah",
		aliases: ["Mic"],
		meta: {
			total_chapters: 7,
			content: [
				{ verses: 16 },
				{ verses: 13 },
				{ verses: 12 },
				{ verses: 13 },
				{ verses: 15 },
				{ verses: 16 },
				{ verses: 20 },
			],
		},
	},
	{
		name: "Nahum",
		aliases: ["Nah"],
		meta: {
			total_chapters: 3,
			content: [{ verses: 15 }, { verses: 13 }, { verses: 19 }],
		},
	},
	{
		name: "Habakkuk",
		aliases: ["Hab"],
		meta: {
			total_chapters: 3,
			content: [{ verses: 17 }, { verses: 20 }, { verses: 19 }],
		},
	},
	{
		name: "Zephaniah",
		aliases: ["Zeph"],
		meta: {
			total_chapters: 3,
			content: [{ verses: 18 }, { verses: 15 }, { verses: 20 }],
		},
	},
	{
		name: "Haggai",
		aliases: ["Hag"],
		meta: { total_chapters: 2, content: [{ verses: 15 }, { verses: 23 }] },
	},
	{
		name: "Zechariah",
		aliases: ["Zech"],
		meta: {
			total_chapters: 14,
			content: [
				{ verses: 21 },
				{ verses: 13 },
				{ verses: 10 },
				{ verses: 14 },
				{ verses: 11 },
				{ verses: 15 },
				{ verses: 14 },
				{ verses: 23 },
				{ verses: 17 },
				{ verses: 12 },
				{ verses: 17 },
				{ verses: 14 },
				{ verses: 9 },
				{ verses: 21 },
			],
		},
	},
	{
		name: "Malachi",
		aliases: ["Mal"],
		meta: {
			total_chapters: 4,
			content: [{ verses: 14 }, { verses: 17 }, { verses: 18 }, { verses: 6 }],
		},
	},
	{
		name: "Matthew",
		aliases: ["Matt"],
		meta: {
			total_chapters: 28,
			content: [
				{ verses: 25 },
				{ verses: 23 },
				{ verses: 17 },
				{ verses: 25 },
				{ verses: 49 },
				{ verses: 34 },
				{ verses: 29 },
				{ verses: 34 },
				{ verses: 38 },
				{ verses: 42 },
				{ verses: 30 },
				{ verses: 49 },
				{ verses: 58 },
				{ verses: 36 },
				{ verses: 39 },
				{ verses: 28 },
				{ verses: 26 },
				{ verses: 34 },
				{ verses: 30 },
				{ verses: 34 },
				{ verses: 46 },
				{ verses: 46 },
				{ verses: 38 },
				{ verses: 51 },
				{ verses: 46 },
				{ verses: 75 },
				{ verses: 66 },
				{ verses: 20 },
			],
		},
	},
	{
		name: "Mark",
		aliases: [],
		meta: {
			total_chapters: 16,
			content: [
				{ verses: 45 },
				{ verses: 28 },
				{ verses: 35 },
				{ verses: 41 },
				{ verses: 43 },
				{ verses: 56 },
				{ verses: 36 },
				{ verses: 38 },
				{ verses: 48 },
				{ verses: 52 },
				{ verses: 32 },
				{ verses: 44 },
				{ verses: 37 },
				{ verses: 72 },
				{ verses: 46 },
				{ verses: 20 },
			],
		},
	},
	{
		name: "Luke",
		aliases: [],
		meta: {
			total_chapters: 24,
			content: [
				{ verses: 80 },
				{ verses: 52 },
				{ verses: 38 },
				{ verses: 44 },
				{ verses: 39 },
				{ verses: 49 },
				{ verses: 50 },
				{ verses: 56 },
				{ verses: 63 },
				{ verses: 42 },
				{ verses: 54 },
				{ verses: 59 },
				{ verses: 35 },
				{ verses: 35 },
				{ verses: 32 },
				{ verses: 31 },
				{ verses: 36 },
				{ verses: 43 },
				{ verses: 48 },
				{ verses: 47 },
				{ verses: 38 },
				{ verses: 71 },
				{ verses: 55 },
				{ verses: 53 },
			],
		},
	},
	{
		name: "John",
		aliases: [],
		meta: {
			total_chapters: 21,
			content: [
				{ verses: 51 },
				{ verses: 25 },
				{ verses: 36 },
				{ verses: 54 },
				{ verses: 47 },
				{ verses: 71 },
				{ verses: 53 },
				{ verses: 60 },
				{ verses: 41 },
				{ verses: 42 },
				{ verses: 57 },
				{ verses: 50 },
				{ verses: 38 },
				{ verses: 31 },
				{ verses: 27 },
				{ verses: 33 },
				{ verses: 26 },
				{ verses: 40 },
				{ verses: 42 },
				{ verses: 31 },
				{ verses: 25 },
			],
		},
	},
	{
		name: "Acts",
		aliases: [],
		meta: {
			total_chapters: 28,
			content: [
				{ verses: 26 },
				{ verses: 47 },
				{ verses: 26 },
				{ verses: 37 },
				{ verses: 42 },
				{ verses: 15 },
				{ verses: 60 },
				{ verses: 39 },
				{ verses: 43 },
				{ verses: 48 },
				{ verses: 30 },
				{ verses: 25 },
				{ verses: 52 },
				{ verses: 28 },
				{ verses: 40 },
				{ verses: 40 },
				{ verses: 34 },
				{ verses: 28 },
				{ verses: 41 },
				{ verses: 38 },
				{ verses: 40 },
				{ verses: 30 },
				{ verses: 35 },
				{ verses: 28 },
				{ verses: 27 },
				{ verses: 32 },
				{ verses: 44 },
				{ verses: 30 },
			],
		},
	},
	{
		name: "Romans",
		aliases: ["Rom"],
		meta: {
			total_chapters: 16,
			content: [
				{ verses: 32 },
				{ verses: 29 },
				{ verses: 31 },
				{ verses: 25 },
				{ verses: 21 },
				{ verses: 23 },
				{ verses: 25 },
				{ verses: 39 },
				{ verses: 33 },
				{ verses: 21 },
				{ verses: 36 },
				{ verses: 21 },
				{ verses: 14 },
				{ verses: 23 },
				{ verses: 33 },
				{ verses: 26 },
			],
		},
	},
	{
		name: "1 Corinthians",
		aliases: ["1 Cor", "1st Cor", "1st Corinthians", "First Corinthians"],
		meta: {
			total_chapters: 16,
			content: [
				{ verses: 31 },
				{ verses: 16 },
				{ verses: 23 },
				{ verses: 21 },
				{ verses: 13 },
				{ verses: 20 },
				{ verses: 40 },
				{ verses: 13 },
				{ verses: 27 },
				{ verses: 33 },
				{ verses: 34 },
				{ verses: 31 },
				{ verses: 13 },
				{ verses: 40 },
				{ verses: 58 },
				{ verses: 24 },
			],
		},
	},
	{
		name: "2 Corinthians",
		aliases: ["2 Cor", "2nd Cor", "2nd Corinthians", "Second Corinthians"],
		meta: {
			total_chapters: 13,
			content: [
				{ verses: 24 },
				{ verses: 17 },
				{ verses: 18 },
				{ verses: 18 },
				{ verses: 21 },
				{ verses: 18 },
				{ verses: 16 },
				{ verses: 24 },
				{ verses: 15 },
				{ verses: 18 },
				{ verses: 33 },
				{ verses: 21 },
				{ verses: 14 },
			],
		},
	},
	{
		name: "Galatians",
		aliases: ["Gal"],
		meta: {
			total_chapters: 6,
			content: [
				{ verses: 24 },
				{ verses: 21 },
				{ verses: 29 },
				{ verses: 31 },
				{ verses: 26 },
				{ verses: 18 },
			],
		},
	},
	{
		name: "Ephesians",
		aliases: ["Eph"],
		meta: {
			total_chapters: 6,
			content: [
				{ verses: 24 },
				{ verses: 22 },
				{ verses: 21 },
				{ verses: 32 },
				{ verses: 33 },
				{ verses: 24 },
			],
		},
	},
	{
		name: "Philippians",
		aliases: ["Phil"],
		meta: {
			total_chapters: 4,
			content: [{ verses: 30 }, { verses: 30 }, { verses: 21 }, { verses: 24 }],
		},
	},
	{
		name: "Colossians",
		aliases: ["Col"],
		meta: {
			total_chapters: 4,
			content: [{ verses: 29 }, { verses: 23 }, { verses: 25 }, { verses: 18 }],
		},
	},
	{
		name: "1 Thessalonians",
		aliases: [
			"1 Thess",
			"1st Thess",
			"1st Thessalonians",
			"First Thessalonians",
		],
		meta: {
			total_chapters: 5,
			content: [
				{ verses: 10 },
				{ verses: 20 },
				{ verses: 13 },
				{ verses: 18 },
				{ verses: 28 },
			],
		},
	},
	{
		name: "2 Thessalonians",
		aliases: [
			"2 Thess",
			"2nd Thess",
			"2nd Thessalonians",
			"Second Thessalonians",
		],
		meta: {
			total_chapters: 3,
			content: [{ verses: 12 }, { verses: 17 }, { verses: 18 }],
		},
	},
	{
		name: "1 Timothy",
		aliases: ["1 Tim", "1st Tim", "1st Timothy", "First Timothy"],
		meta: {
			total_chapters: 6,
			content: [
				{ verses: 20 },
				{ verses: 15 },
				{ verses: 16 },
				{ verses: 16 },
				{ verses: 25 },
				{ verses: 21 },
			],
		},
	},
	{
		name: "2 Timothy",
		aliases: ["2 Tim", "2nd Tim", "2nd Timothy", "Second Timothy"],
		meta: {
			total_chapters: 4,
			content: [{ verses: 18 }, { verses: 26 }, { verses: 17 }, { verses: 22 }],
		},
	},
	{
		name: "Titus",
		aliases: [],
		meta: {
			total_chapters: 3,
			content: [{ verses: 16 }, { verses: 15 }, { verses: 15 }],
		},
	},
	{
		name: "Philemon",
		aliases: ["Phlm"],
		meta: { total_chapters: 1, content: [{ verses: 26 }] },
	},
	{
		name: "Hebrews",
		aliases: ["Heb"],
		meta: {
			total_chapters: 13,
			content: [
				{ verses: 14 },
				{ verses: 18 },
				{ verses: 19 },
				{ verses: 16 },
				{ verses: 14 },
				{ verses: 20 },
				{ verses: 28 },
				{ verses: 13 },
				{ verses: 28 },
				{ verses: 39 },
				{ verses: 40 },
				{ verses: 29 },
				{ verses: 25 },
			],
		},
	},
	{
		name: "James",
		aliases: ["Jas"],
		meta: {
			total_chapters: 5,
			content: [
				{ verses: 27 },
				{ verses: 26 },
				{ verses: 18 },
				{ verses: 17 },
				{ verses: 20 },
			],
		},
	},
	{
		name: "1 Peter",
		aliases: ["1 Pet", "1st Pet", "1st Peter", "First Peter"],
		meta: {
			total_chapters: 5,
			content: [
				{ verses: 25 },
				{ verses: 25 },
				{ verses: 22 },
				{ verses: 19 },
				{ verses: 14 },
			],
		},
	},
	{
		name: "2 Peter",
		aliases: ["2 Pet", "2nd Pet", "2nd Peter", "Second Peter"],
		meta: {
			total_chapters: 3,
			content: [{ verses: 21 }, { verses: 22 }, { verses: 18 }],
		},
	},
	{
		name: "1 John",
		aliases: ["1st John", "First John"],
		meta: {
			total_chapters: 5,
			content: [
				{ verses: 10 },
				{ verses: 29 },
				{ verses: 24 },
				{ verses: 21 },
				{ verses: 21 },
			],
		},
	},
	{
		name: "2 John",
		aliases: ["2nd John", "Second John"],
		meta: { total_chapters: 1, content: [{ verses: 14 }] },
	},
	{
		name: "3 John",
		aliases: ["3rd John", "Third John"],
		meta: { total_chapters: 1, content: [{ verses: 16 }] },
	},
	{
		name: "Jude",
		aliases: [],
		meta: { total_chapters: 1, content: [{ verses: 26 }] },
	},
	{
		name: "Revelation",
		aliases: ["Rev"],
		meta: {
			total_chapters: 22,
			content: [
				{ verses: 20 },
				{ verses: 29 },
				{ verses: 22 },
				{ verses: 11 },
				{ verses: 14 },
				{ verses: 17 },
				{ verses: 17 },
				{ verses: 13 },
				{ verses: 21 },
				{ verses: 11 },
				{ verses: 19 },
				{ verses: 17 },
				{ verses: 18 },
				{ verses: 20 },
				{ verses: 8 },
				{ verses: 21 },
				{ verses: 18 },
				{ verses: 24 },
				{ verses: 21 },
				{ verses: 15 },
				{ verses: 27 },
				{ verses: 21 },
			],
		},
	},
];
export { BOOKS };
